### ISSUE TITLE
update to amqlib 0.8.0

### ISSUE THREAD

**Issue by francois-spectre** [twawszczak/amqplib-as-promised#5]
is there a plan to update to the last version of amqlib?
I would like to use node v16 but looks like amqlib 0.5 is not compatible:
```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'amqplib@0.5.6',
npm WARN EBADENGINE   required: { node: '>=0.8 <=12' },
npm WARN EBADENGINE   current: { node: 'v16.13.0', npm: '8.1.0' }
npm WARN EBADENGINE }
```

**Comment by dex4er** [comment]
https://www.npmjs.com/package/amqplib-as-promised/v/4.1.0 is released.

Thanks for report.
